/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}", "./screens/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      fontFamily: {
        space: ["Space Grotesk", "sans-serif"],
      },
      colors: {
        "surface-variant": "#323442",
        "on-secondary": "#3f008e",
        "primary-container": "#06b6d4",
        "background": "#10131f",
        "on-tertiary-fixed-variant": "#7a3000",
        "tertiary-fixed": "#ffdbcb",
        "on-error": "#690005",
        "secondary-fixed-dim": "#d2bbff",
        "on-secondary-fixed": "#25005a",
        "on-tertiary": "#562000",
        "inverse-surface": "#e1e1f3",
        "error-container": "#93000a",
        "surface-bright": "#363846",
        "on-primary": "#003640",
        "primary-fixed-dim": "#4cd7f6",
        "tertiary": "#ffb692",
        "surface": "#10131f",
        "secondary": "#d2bbff",
        "surface-container-high": "#272937",
        "error": "#ffb4ab",
        "on-error-container": "#ffdad6",
        "surface-tint": "#4cd7f6",
        "surface-container-highest": "#323442",
        "outline-variant": "#3d494c",
        "primary": "#4cd7f6",
        "on-secondary-fixed-variant": "#5a00c6",
        "on-secondary-container": "#c9aeff",
        "secondary-container": "#6001d1",
        "on-primary-fixed": "#001f26",
        "surface-container-low": "#191b28",
        "inverse-on-surface": "#2e303d",
        "tertiary-fixed-dim": "#ffb692",
        "outline": "#869397",
        "secondary-fixed": "#eaddff",
        "surface-container": "#1d1f2c",
        "on-surface": "#e1e1f3",
        "on-surface-variant": "#bcc9cd",
        "tertiary-container": "#ff8440",
        "surface-dim": "#10131f",
        "on-primary-fixed-variant": "#004e5c",
        "on-background": "#e1e1f3",
        "on-tertiary-fixed": "#341100",
        "primary-fixed": "#acedff",
        "on-tertiary-container": "#682800",
        "inverse-primary": "#00687a",
        "surface-container-lowest": "#0b0d1a",
        "on-primary-container": "#00424f"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "element-gap-lg": "32px",
        "gutter": "16px",
        "element-gap-md": "16px",
        "element-gap-sm": "8px",
        "unit": "8px",
        "container-padding-desktop": "40px",
        "container-padding-mobile": "20px"
      }
    },
  },
  plugins: [],
}
