export interface WordItem {
  word: string;
  description: string;
}

export type CategoryId = 'space' | 'animals' | 'food' | 'sports' | 'anything';

export const categoryWords = {
  "space": [
    {
      "word": "MOON",
      "description": "The natural satellite orbiting planet Earth."
    },
    {
      "word": "MARS",
      "description": "The Red Planet, fourth from the Sun."
    },
    {
      "word": "STAR",
      "description": "Luminous celestial sphere of hot plasma."
    },
    {
      "word": "LUNA",
      "description": "Latin name for Earth's silvery moon."
    },
    {
      "word": "NOVA",
      "description": "A star showing a sudden large increase in brightness."
    },
    {
      "word": "VOID",
      "description": "The vast empty space between cosmic bodies."
    },
    {
      "word": "DUST",
      "description": "Microscopic cosmic particles scattered in nebulae."
    },
    {
      "word": "RING",
      "description": "A band of ice and rock orbiting a gas planet."
    },
    {
      "word": "HALO",
      "description": "A luminous spherical glow around a galaxy or star."
    },
    {
      "word": "TAIL",
      "description": "Streaming gas and dust trailing behind a comet."
    },
    {
      "word": "BEAM",
      "description": "A concentrated ray of light radiating through space."
    },
    {
      "word": "AXIS",
      "description": "An imaginary line around which a celestial body spins."
    },
    {
      "word": "ZONE",
      "description": "A specific celestial region, such as the habitable zone."
    },
    {
      "word": "AURA",
      "description": "A radiant corona surrounding a celestial object."
    },
    {
      "word": "FLUX",
      "description": "The flow rate of energy or particles per unit area."
    },
    {
      "word": "CORE",
      "description": "The ultra-dense central interior of a star or planet."
    },
    {
      "word": "MIST",
      "description": "A diffuse cloud of gaseous vapor in deep space."
    },
    {
      "word": "GLOW",
      "description": "Soft radiant luminescence emitted by nebulae."
    },
    {
      "word": "DARK",
      "description": "The absence of light in deep interstellar space."
    },
    {
      "word": "WAVE",
      "description": "Gravitational or electromagnetic energy ripples."
    },
    {
      "word": "WARP",
      "description": "Curvature or distortion of the spacetime fabric."
    },
    {
      "word": "APEX",
      "description": "The highest point or orbital apogee reached."
    },
    {
      "word": "NODE",
      "description": "Intersection point where an orbit crosses a plane."
    },
    {
      "word": "DEEP",
      "description": "The far reaches of deep cosmic space."
    },
    {
      "word": "FUSE",
      "description": "Nuclear fusion process powering star cores."
    },
    {
      "word": "DAWN",
      "description": "The earliest light breaking across a planetary horizon."
    },
    {
      "word": "DUSK",
      "description": "Twilight shadow falling over a celestial hemisphere."
    },
    {
      "word": "ECHO",
      "description": "Reflected radio wave bounced off a celestial object."
    },
    {
      "word": "GATE",
      "description": "Hypothetical hyperspace jump point or portal."
    },
    {
      "word": "SAIL",
      "description": "Solar sail propelled by photon radiation pressure."
    },
    {
      "word": "MASS",
      "description": "The fundamental quantity of matter in a cosmic body."
    },
    {
      "word": "ZERO",
      "description": "Zero gravity conditions experienced in orbital freefall."
    },
    {
      "word": "COLD",
      "description": "Near absolute zero temperature of outer space."
    },
    {
      "word": "HEAT",
      "description": "Thermal energy generated by stellar nuclear reactions."
    },
    {
      "word": "LENS",
      "description": "Gravitational bending of light by massive clusters."
    },
    {
      "word": "ORBS",
      "description": "Spherical planets, moons, or luminous stars."
    },
    {
      "word": "PEAK",
      "description": "Highest altitude mountain or crater summit on a moon."
    },
    {
      "word": "WIND",
      "description": "Stream of charged particles known as solar wind."
    },
    {
      "word": "NEON",
      "description": "Noble gas glowing brightly in stellar emission lines."
    },
    {
      "word": "TIME",
      "description": "The fourth dimension intertwined in spacetime continuum."
    },
    {
      "word": "ORBIT",
      "description": "Curved gravitationally curved trajectory around a mass."
    },
    {
      "word": "STARS",
      "description": "Giant shining balls of burning hydrogen and helium."
    },
    {
      "word": "COMET",
      "description": "Icy small solar system body releasing gas and dust."
    },
    {
      "word": "EARTH",
      "description": "The third planet from the Sun, our vibrant home."
    },
    {
      "word": "PLUTO",
      "description": "Famous dwarf planet located in the distant Kuiper Belt."
    },
    {
      "word": "VENUS",
      "description": "Second planet from the Sun with a scorching atmosphere."
    },
    {
      "word": "TITAN",
      "description": "Saturn's giant moon with dense atmosphere and methane lakes."
    },
    {
      "word": "ATLAS",
      "description": "Small inner moon of Saturn and cosmic celestial map."
    },
    {
      "word": "SOLAR",
      "description": "Relating to our Sun and its surrounding planetary system."
    },
    {
      "word": "LUNAR",
      "description": "Relating to Earth's moon and its cratered surface."
    },
    {
      "word": "SPACE",
      "description": "The infinite expanse where stars, planets, and galaxies exist."
    },
    {
      "word": "ROVER",
      "description": "Automated planetary exploration robotic vehicle."
    },
    {
      "word": "FLARE",
      "description": "Sudden intense eruption of electromagnetic radiation on a star."
    },
    {
      "word": "ORION",
      "description": "Prominent winter constellation known as the Hunter."
    },
    {
      "word": "VESTA",
      "description": "One of the largest asteroids in the main asteroid belt."
    },
    {
      "word": "CERES",
      "description": "The largest asteroid and dwarf planet in the asteroid belt."
    },
    {
      "word": "DENEB",
      "description": "Brilliant blue-white supergiant star in the Cygnus constellation."
    },
    {
      "word": "SPICA",
      "description": "Brightest binary star system in the Virgo constellation."
    },
    {
      "word": "RIGEL",
      "description": "Luminous blue supergiant star in the Orion constellation."
    },
    {
      "word": "HYDRA",
      "description": "The largest of the 88 modern constellations."
    },
    {
      "word": "DRACO",
      "description": "Constellation representing a celestial dragon in the northern sky."
    },
    {
      "word": "ARIES",
      "description": "Zodiac constellation named after the mythological Ram."
    },
    {
      "word": "LIBRA",
      "description": "Zodiac constellation symbolizing celestial balance."
    },
    {
      "word": "PLUME",
      "description": "Geyser plume of water vapor venting into space from ice moons."
    },
    {
      "word": "STORM",
      "description": "Turbulent cosmic cyclone like Jupiter's Great Red Spot."
    },
    {
      "word": "LIGHT",
      "description": "Electromagnetic radiation traveling at cosmic speed limit."
    },
    {
      "word": "NIGHT",
      "description": "Period of darkness when a planet faces away from its star."
    },
    {
      "word": "PHASE",
      "description": "Changing shape of the sunlit portion of a moon or planet."
    },
    {
      "word": "ASTRO",
      "description": "Prefix relating to the stars, celestial space, and cosmos."
    },
    {
      "word": "ALIEN",
      "description": "Hypothetical extraterrestrial life from beyond Earth."
    },
    {
      "word": "UMBRA",
      "description": "The fully shaded inner region of a cosmic shadow during eclipse."
    },
    {
      "word": "PROBE",
      "description": "Unmanned robotic spacecraft sent to explore deep space."
    },
    {
      "word": "RADAR",
      "description": "Radio detection system used to map planetary surfaces."
    },
    {
      "word": "GIANT",
      "description": "Extremely large luminous star in late evolutionary phase."
    },
    {
      "word": "DWARF",
      "description": "Small low-mass or remnant star such as a white dwarf."
    },
    {
      "word": "ALPHA",
      "description": "Primary or brightest star in a constellation system."
    },
    {
      "word": "DELTA",
      "description": "Fourth brightest star or delta-V velocity change metric."
    },
    {
      "word": "GAMMA",
      "description": "High-energy electromagnetic rays from supernova explosions."
    },
    {
      "word": "CRAFT",
      "description": "Orbital or interplanetary exploratory spaceship."
    },
    {
      "word": "CLOUD",
      "description": "Dense molecular gas formation giving birth to new stars."
    },
    {
      "word": "MESON",
      "description": "Subatomic hadron particle composed of a quark and antiquark."
    },
    {
      "word": "GLOBE",
      "description": "A spherical celestial sphere or planetary body."
    },
    {
      "word": "IONIC",
      "description": "Relating to charged particles in ion engine propulsion."
    },
    {
      "word": "LASER",
      "description": "Coherent beam used in deep space optical communications."
    },
    {
      "word": "OASIS",
      "description": "Habitable planet or biosphere amid barren cosmic reaches."
    },
    {
      "word": "POLAR",
      "description": "Relating to the magnetic or rotational poles of a planet."
    },
    {
      "word": "PULSE",
      "description": "Periodic burst of electromagnetic radiation from a pulsar."
    },
    {
      "word": "QUARK",
      "description": "Fundamental particle composing matter inside dense star remnants."
    },
    {
      "word": "RADIO",
      "description": "Long wavelength signals used by radio telescope observatories."
    },
    {
      "word": "RELIC",
      "description": "Ancient cosmic background radiation from the early universe."
    },
    {
      "word": "ROBOT",
      "description": "Autonomous explorer operating in extreme planetary climates."
    },
    {
      "word": "SHINE",
      "description": "Brilliance radiating from a star or reflective ice ring."
    },
    {
      "word": "SONIC",
      "description": "Shockwaves generated in dense supernova blast fronts."
    },
    {
      "word": "SPARK",
      "description": "Electrostatic discharge sparking across planetary rings."
    },
    {
      "word": "SWARM",
      "description": "Dyson swarm constellation of satellites collecting solar energy."
    },
    {
      "word": "TIDES",
      "description": "Gravitational deformations caused by nearby massive bodies."
    },
    {
      "word": "TRAIL",
      "description": "Luminous ion trail left behind high velocity meteoroids."
    },
    {
      "word": "ULTRA",
      "description": "Extreme energy band such as ultraviolet cosmic spectra."
    },
    {
      "word": "VAPOR",
      "description": "Sublimating water or methane gas in comet tails."
    },
    {
      "word": "XENON",
      "description": "Heavy noble gas used as propellant in ion spacecraft drives."
    },
    {
      "word": "YIELD",
      "description": "Total energy output released by stellar thermonuclear fusion."
    },
    {
      "word": "AURAE",
      "description": "Luminous electromagnetic halos around distant stars."
    },
    {
      "word": "BLAZE",
      "description": "Fierce radiation outburst ignited during coronal mass ejections."
    },
    {
      "word": "BOUND",
      "description": "Gravitationally locked in orbit around a parent star."
    },
    {
      "word": "CHUTE",
      "description": "Atmospheric reentry parachute slowing a return capsule."
    },
    {
      "word": "CRASH",
      "description": "Impact of a meteoroid striking a planetary crust."
    },
    {
      "word": "DRIFT",
      "description": "Gradual orbital decay or stellar drift across the galaxy."
    },
    {
      "word": "EVENT",
      "description": "Cosmic occurrence like a supernova or gamma-ray burst."
    },
    {
      "word": "FOCUS",
      "description": "Focal point of a parabolic telescope mirror or detector."
    },
    {
      "word": "FORGE",
      "description": "Cosmic nucleosynthesis forging elements inside star cores."
    },
    {
      "word": "COSMIC",
      "description": "Relating to the universe or cosmos."
    },
    {
      "word": "GALAXY",
      "description": "A massive gravitationally bound system of stars and dark matter."
    },
    {
      "word": "NEBULA",
      "description": "A giant interstellar cloud of dust and hydrogen gas."
    },
    {
      "word": "METEOR",
      "description": "A streak of light caused by a space rock burning in the atmosphere."
    },
    {
      "word": "AURORA",
      "description": "Luminous natural light display in a planet's polar sky."
    },
    {
      "word": "ROCKET",
      "description": "A missile or spacecraft propelled by chemical rocket engines."
    },
    {
      "word": "PULSAR",
      "description": "A rapidly rotating magnetized neutron star emitting regular pulses."
    },
    {
      "word": "QUASAR",
      "description": "An extremely luminous active galactic nucleus powered by a black hole."
    },
    {
      "word": "PLANET",
      "description": "A celestial body orbiting a star that has cleared its orbital neighborhood."
    },
    {
      "word": "SATURN",
      "description": "The sixth planet from the Sun, celebrated for its spectacular rings."
    },
    {
      "word": "CRATER",
      "description": "A large bowl-shaped cavity on a planet caused by meteorite impact."
    },
    {
      "word": "VACUUM",
      "description": "A space entirely devoid of matter, like the deep void of space."
    },
    {
      "word": "ZENITH",
      "description": "The celestial point directly above an observer on the ground."
    },
    {
      "word": "SPHERE",
      "description": "A perfectly round 3D celestial object like a moon or planet."
    },
    {
      "word": "FLIGHT",
      "description": "The trajectory or orbital journey of a spacecraft through space."
    },
    {
      "word": "PHOTON",
      "description": "A quantum particle of light carrying electromagnetic energy."
    },
    {
      "word": "STELLA",
      "description": "Latin word for star, used in astronomical designations."
    },
    {
      "word": "SYSTEM",
      "description": "A gravitationally bound collection of planets and asteroids around a star."
    },
    {
      "word": "CORONA",
      "description": "The outermost layer of the Sun's plasma atmosphere."
    },
    {
      "word": "APOLLO",
      "description": "Historic NASA spaceflight program that landed humans on the Moon."
    },
    {
      "word": "HUBBLE",
      "description": "Famous orbiting space telescope that revolutionized modern astronomy."
    },
    {
      "word": "MIRROR",
      "description": "Polished optical surface reflecting starlight in giant telescopes."
    },
    {
      "word": "OPTICS",
      "description": "The branch of physics that studies behavior and properties of light."
    },
    {
      "word": "SENSOR",
      "description": "Electronic instrument detecting radiation and magnetic fields."
    },
    {
      "word": "THRUST",
      "description": "Propulsive force produced by a spacecraft rocket engine."
    },
    {
      "word": "VECTOR",
      "description": "A directional velocity vector defining orbital trajectories."
    },
    {
      "word": "BEACON",
      "description": "Navigation radio pulse transmitter installed on orbital stations."
    },
    {
      "word": "MATRIX",
      "description": "Mathematical coordinate grid mapping interstellar space."
    },
    {
      "word": "CANOPY",
      "description": "The expansive overarching celestial sphere of stars in the night sky."
    },
    {
      "word": "APOGEE",
      "description": "The point in an elliptical orbit furthest from Earth."
    },
    {
      "word": "MODULE",
      "description": "A self-contained functional unit of a space station or lander."
    },
    {
      "word": "ORBITS",
      "description": "Gravitational revolution pathways traversed by celestial bodies."
    },
    {
      "word": "RADIAN",
      "description": "Angular unit used to calculate celestial trajectories and distances."
    },
    {
      "word": "SIGNAL",
      "description": "Radio frequency transmission received from deep space explorers."
    },
    {
      "word": "TARGET",
      "description": "Destination asteroid, comet, or planet targeted for mission flyby."
    },
    {
      "word": "VOYAGE",
      "description": "Long-duration interplanetary expedition across the solar system."
    },
    {
      "word": "METRIC",
      "description": "Mathematical spacetime tensor metric describing cosmic curvature."
    },
    {
      "word": "SHIELD",
      "description": "Thermal heat shield protecting a lander capsule during atmospheric entry."
    },
    {
      "word": "CARBON",
      "description": "Essential element formed in star cores and found in carbonaceous asteroids."
    },
    {
      "word": "HELIUM",
      "description": "Second most abundant element in the universe, fuel for red giant stars."
    },
    {
      "word": "OXYGEN",
      "description": "Vital element forged in massive stars and present in planetary atmospheres."
    },
    {
      "word": "SILICA",
      "description": "Silicate mineral making up the bulk of stony asteroids and terrestrial crusts."
    },
    {
      "word": "MAGNET",
      "description": "Powerful magnetic field deflecting cosmic radiation around planets."
    },
    {
      "word": "PLASMA",
      "description": "Fourth state of matter consisting of superheated ionized gas in stars."
    },
    {
      "word": "ENERGY",
      "description": "The capacity of stellar radiation and nuclear reactions to do work."
    },
    {
      "word": "DOCKER",
      "description": "Automated docking mechanism connecting spacecraft in orbit."
    },
    {
      "word": "ENGINE",
      "description": "Liquid propellant or ion thruster engine driving cosmic explorers."
    },
    {
      "word": "ESCAPE",
      "description": "Escape velocity required to break free from a planet's gravitational pull."
    },
    {
      "word": "EXPAND",
      "description": "The continuous metric expansion of the universe since the Big Bang."
    },
    {
      "word": "FREEZE",
      "description": "Cryogenic temperatures freezing volatile gases on outer solar system moons."
    },
    {
      "word": "FUSION",
      "description": "Thermonuclear fusion process that ignites and powers active stars."
    },
    {
      "word": "GEYSER",
      "description": "Cryovolcanic eruption venting water vapor into space from icy moons."
    },
    {
      "word": "IMPACT",
      "description": "High-speed collision of a meteoroid creating a crater on a planetary surface."
    },
    {
      "word": "LAUNCH",
      "description": "The liftoff and ascent of a rocket from a planetary launchpad."
    },
    {
      "word": "MINING",
      "description": "Extracting precious metals and water ice from near-Earth asteroids."
    },
    {
      "word": "MOTION",
      "description": "Keplerian orbital dynamics describing planetary revolutions."
    },
    {
      "word": "OUTPUT",
      "description": "Luminosity and total radiant energy emitted by a star per second."
    },
    {
      "word": "PERIOD",
      "description": "The time taken for a celestial body to complete one full orbit."
    },
    {
      "word": "RADIUS",
      "description": "The distance from the center of a celestial body to its surface."
    },
    {
      "word": "REFLEX",
      "description": "Gravitational wobble of a star induced by an orbiting exoplanet."
    },
    {
      "word": "REMOTE",
      "description": "Remote sensing observation of planetary geology from orbital satellites."
    },
    {
      "word": "SECTOR",
      "description": "Designated astronomical coordinate sector of the galactic plane."
    },
    {
      "word": "SOURCE",
      "description": "High-energy cosmic ray source in a distant active galactic nucleus."
    },
    {
      "word": "STATIC",
      "description": "Background cosmic static noise from the Big Bang relic radiation."
    },
    {
      "word": "SURVEY",
      "description": "Deep space astronomical sky survey mapping distant galaxies."
    },
    {
      "word": "TUNNEL",
      "description": "Hypothetical Einstein-Rosen bridge wormhole connecting distant regions."
    },
    {
      "word": "VESSEL",
      "description": "Crewed exploratory vessel traversing deep interplanetary space."
    },
    {
      "word": "VERTEX",
      "description": "Intersection vertex of celestial coordinate grid lines in star maps."
    },
    {
      "word": "WEIGHT",
      "description": "The gravitational force exerted on an object by a celestial body."
    },
    {
      "word": "ZODIAC",
      "description": "The belt of the celestial sphere through which the Sun and planets pass."
    },
    {
      "word": "ALBEDO",
      "description": "Reflectivity coefficient of a planetary surface or asteroid."
    },
    {
      "word": "ASTRAL",
      "description": "Relating to or emanating from the stars or cosmic realms."
    },
    {
      "word": "ASTERO",
      "description": "Rocky metallic body orbiting the Sun in the inner solar system."
    },
    {
      "word": "BINARY",
      "description": "Star system consisting of two stars gravitationally orbiting each other."
    },
    {
      "word": "COSMOS",
      "description": "The universe seen as a well-ordered and harmonious whole."
    },
    {
      "word": "CRADLE",
      "description": "Dense molecular cloud serving as stellar nursery for newborn stars."
    },
    {
      "word": "CYGNUS",
      "description": "Prominent northern constellation known as the Swan containing Cygnus X-1."
    },
    {
      "word": "EMITTR",
      "description": "Source emitting electromagnetic radiation across cosmic distances."
    },
    {
      "word": "EXODUS",
      "description": "Interstellar migration journey of exploratory fleet to distant worlds."
    },
    {
      "word": "FLARES",
      "description": "Energetic magnetic outbursts erupting from active stellar atmospheres."
    },
    {
      "word": "IGNITE",
      "description": "Core compression triggering thermonuclear ignition inside protostars."
    },
    {
      "word": "OCCULT",
      "description": "Phenomenon when a celestial body passes in front of another from view."
    },
    {
      "word": "ORBITL",
      "description": "Trajectory relating to movement in an orbital curve around a planet."
    },
    {
      "word": "SHADOW",
      "description": "Region where direct starlight is blocked by a planetary body."
    },
    {
      "word": "SOLARS",
      "description": "Energy systems harnessing direct radiant energy from a host star."
    },
    {
      "word": "SPECTM",
      "description": "Electromagnetic spectrum analyzed via astronomical spectrographs."
    },
    {
      "word": "SPIRAL",
      "description": "Pinwheel structure characteristic of grand design spiral galaxies."
    },
    {
      "word": "STELLR",
      "description": "Relating to stars, stellar atmospheres, and nuclear lifecycles."
    },
    {
      "word": "TETHYS",
      "description": "Mid-sized icy moon of Saturn with a massive impact crater named Odysseus."
    },
    {
      "word": "URANUS",
      "description": "Seventh planet from the Sun, an ice giant tipped on its side."
    }
  ],
  "animals": [
    {
      "word": "LION",
      "description": "The majestic king of the African savannah."
    },
    {
      "word": "BEAR",
      "description": "Large powerful mammal with thick fur and sharp claws."
    },
    {
      "word": "WOLF",
      "description": "Wild canine predator that hunts in organized packs."
    },
    {
      "word": "DEER",
      "description": "Graceful herbivore known for branching antlers."
    },
    {
      "word": "DUCK",
      "description": "Waterbird with webbed feet and waterproof feathers."
    },
    {
      "word": "FROG",
      "description": "Amphibian known for high jumps and amphibious life."
    },
    {
      "word": "CRAB",
      "description": "Crustacean with a hard exoskeleton and pincer claws."
    },
    {
      "word": "GOAT",
      "description": "Agile horned mammal expert at navigating mountain cliffs."
    },
    {
      "word": "HARE",
      "description": "Fast-running mammal with long ears and strong hind legs."
    },
    {
      "word": "HAWK",
      "description": "Sharp-eyed bird of prey that swoops down on prey."
    },
    {
      "word": "MOLE",
      "description": "Burrowing mammal adapted for subterranean digging."
    },
    {
      "word": "MULE",
      "description": "Strong pack animal, a hybrid of donkey and horse."
    },
    {
      "word": "SEAL",
      "description": "Semi-aquatic marine mammal with sleek flippers."
    },
    {
      "word": "SWAN",
      "description": "Elegant large waterfowl known for graceful long necks."
    },
    {
      "word": "TOAD",
      "description": "Dry-skinned warty amphibian active primarily at dusk."
    },
    {
      "word": "BULL",
      "description": "Powerful adult male bovine with formidable horns."
    },
    {
      "word": "CALF",
      "description": "Young bovine or offspring of a whale or elephant."
    },
    {
      "word": "COLT",
      "description": "Young male horse under four years old."
    },
    {
      "word": "CROW",
      "description": "Highly intelligent black corvid bird with strong problem-solving skills."
    },
    {
      "word": "DOVE",
      "description": "Gentle bird symbolizing peace and harmonious nature."
    },
    {
      "word": "EELS",
      "description": "Elongated snake-like fish swimming in marine depths."
    },
    {
      "word": "FAWN",
      "description": "Young spotted deer in its first year of life."
    },
    {
      "word": "FOAL",
      "description": "Young equine horse or donkey offspring."
    },
    {
      "word": "GULL",
      "description": "Seabird found near coastal shorelines and oceans."
    },
    {
      "word": "IBIS",
      "description": "Long-legged wading bird with a slender downcurved bill."
    },
    {
      "word": "LARK",
      "description": "Small songbird famous for melodious aerial singing."
    },
    {
      "word": "LYNX",
      "description": "Wild feline with tufted ears and thick winter coat."
    },
    {
      "word": "MARE",
      "description": "Mature female horse or pony."
    },
    {
      "word": "MINK",
      "description": "Sleek semi-aquatic carnivore prized for waterproof fur."
    },
    {
      "word": "MOTH",
      "description": "Nocturnal winged insect attracted to moonlight."
    },
    {
      "word": "NEWT",
      "description": "Small brightly colored semi-aquatic salamander."
    },
    {
      "word": "ORCA",
      "description": "Apex marine mammal predator also known as killer whale."
    },
    {
      "word": "PIKE",
      "description": "Predatory freshwater fish with a long slender body."
    },
    {
      "word": "PUMA",
      "description": "Large solitary wild cat native to the Americas."
    },
    {
      "word": "RAMS",
      "description": "Male wild bighorn sheep with curved horns."
    },
    {
      "word": "STAG",
      "description": "Majestic adult male deer with fully grown antlers."
    },
    {
      "word": "TUNA",
      "description": "Fast-swimming saltwater apex fish prized worldwide."
    },
    {
      "word": "VOLE",
      "description": "Small rodent resembling a mouse with a shorter tail."
    },
    {
      "word": "WASP",
      "description": "Slender stinging insect building intricate paper nests."
    },
    {
      "word": "YAKS",
      "description": "Long-haired domesticated bovid native to Himalayan heights."
    },
    {
      "word": "TIGER",
      "description": "Largest wild cat species with distinctive dark stripes."
    },
    {
      "word": "ZEBRA",
      "description": "African wild horse with black-and-white striped coats."
    },
    {
      "word": "EAGLE",
      "description": "Majestic bird of prey with keen eyesight and powerful talons."
    },
    {
      "word": "SHARK",
      "description": "Apex marine predator with cartilage skeleton and razor teeth."
    },
    {
      "word": "WHALE",
      "description": "Giant marine mammal swimming in oceans across the globe."
    },
    {
      "word": "PANDA",
      "description": "Beloved black-and-white bear native to Chinese bamboo forests."
    },
    {
      "word": "KOALA",
      "description": "Arboreal Australian marsupial feeding on eucalyptus leaves."
    },
    {
      "word": "OTTER",
      "description": "Playful semi-aquatic mammal skilled at swimming and tool use."
    },
    {
      "word": "CAMEL",
      "description": "Desert ungulate adapted with water-retaining humps."
    },
    {
      "word": "BISON",
      "description": "Massive heavy-headed wild bovine roaming grasslands."
    },
    {
      "word": "LLAMA",
      "description": "South American domesticated camelid with soft wool."
    },
    {
      "word": "LEMUR",
      "description": "Arboreal primate native strictly to the island of Madagascar."
    },
    {
      "word": "MOOSE",
      "description": "Largest deer species with broad palmate antlers."
    },
    {
      "word": "HYENA",
      "description": "Savannah carnivore known for powerful jaws and social clans."
    },
    {
      "word": "VIPER",
      "description": "Venomous snake with long hinged fangs."
    },
    {
      "word": "GECKO",
      "description": "Small nocturnal lizard with specialized clinging toe pads."
    },
    {
      "word": "CORAL",
      "description": "Marine invertebrate building vibrant ocean reef ecosystems."
    },
    {
      "word": "SQUID",
      "description": "Fast cephalopod with ten arms and dynamic camouflage."
    },
    {
      "word": "CRANE",
      "description": "Tall long-legged wading bird famous for courtship dances."
    },
    {
      "word": "HERON",
      "description": "Coastal wading bird with long spear-like bill."
    },
    {
      "word": "STORK",
      "description": "Large wading bird that builds enormous stick nests."
    },
    {
      "word": "RAVEN",
      "description": "Large black bird renowned for complex intelligence."
    },
    {
      "word": "ROBIN",
      "description": "Familiar songbird with a cheerful red-orange breast."
    },
    {
      "word": "FINCH",
      "description": "Small seed-eating bird with a specialized stout beak."
    },
    {
      "word": "SLOTH",
      "description": "Slow-moving arboreal mammal hanging upside down in rainforests."
    },
    {
      "word": "COBRA",
      "description": "Venomous elapid snake that spreads an intimidating hood."
    },
    {
      "word": "DINGO",
      "description": "Wild canine native to Australia with golden-yellow coat."
    },
    {
      "word": "GUPPY",
      "description": "Colorful small freshwater aquarium fish."
    },
    {
      "word": "HIPPO",
      "description": "Massive semi-aquatic African mammal with large tusks."
    },
    {
      "word": "HORSE",
      "description": "Domesticated one-toed hoofed mammal prized for speed and power."
    },
    {
      "word": "HOUND",
      "description": "Hunting dog breed with acute sense of smell or sight."
    },
    {
      "word": "HYRAX",
      "description": "Small furry herbivore closely related genetically to elephants."
    },
    {
      "word": "INDRI",
      "description": "The largest living lemur native to eastern Madagascar."
    },
    {
      "word": "LORIS",
      "description": "Nocturnal slow-moving primate with large forward-facing eyes."
    },
    {
      "word": "MAMBA",
      "description": "Extremely fast and venomous tree-dwelling African snake."
    },
    {
      "word": "MANTA",
      "description": "Large graceful ocean ray gliding with wing-like fins."
    },
    {
      "word": "MORAY",
      "description": "Secretive predatory reef eel lurking in coral crevices."
    },
    {
      "word": "OKAPI",
      "description": "Forest giraffe relative with zebra-like striped hindquarters."
    },
    {
      "word": "PERCH",
      "description": "Freshwater game fish with spiny dorsal fins."
    },
    {
      "word": "PRAWN",
      "description": "Large swimming crustacean found in fresh and saltwater."
    },
    {
      "word": "RHINO",
      "description": "Large herbivore characterized by one or two keratin horns."
    },
    {
      "word": "SAIGA",
      "description": "Critically endangered antelope with a distinctive bulbous snout."
    },
    {
      "word": "SKINK",
      "description": "Smooth-scaled lizard that can shed its tail to escape predators."
    },
    {
      "word": "SKUNK",
      "description": "Black-and-white mammal that defends itself with noxious spray."
    },
    {
      "word": "SNAKE",
      "description": "Limbless elongated carnivorous reptile of the suborder Serpentes."
    },
    {
      "word": "SNIPE",
      "description": "Cryptic wading bird with long slender probing bill."
    },
    {
      "word": "TAPIR",
      "description": "Jungle herbivore with a short prehensile snout."
    },
    {
      "word": "TROUT",
      "description": "Freshwater fish belonging to the salmon family."
    },
    {
      "word": "XERUS",
      "description": "African ground squirrel living in arid savannah burrows."
    },
    {
      "word": "YAPOK",
      "description": "Aquatic marsupial with webbed feet and waterproof pouch."
    },
    {
      "word": "ANOAS",
      "description": "Smallest wild cattle species endemic to Indonesian forests."
    },
    {
      "word": "BONGO",
      "description": "Striking reddish-brown forest antelope with white side stripes."
    },
    {
      "word": "CIVET",
      "description": "Small nocturnal mammal valued for historical perfumery musk."
    },
    {
      "word": "COATI",
      "description": "South American mammal with flexible snout and banded tail."
    },
    {
      "word": "DHOLE",
      "description": "Asiatic wild dog that hunts in cooperative packs."
    },
    {
      "word": "EGRET",
      "description": "Graceful white wading bird with long elegant neck feathers."
    },
    {
      "word": "MACAW",
      "description": "Large brightly colored long-tailed parrot of tropical Americas."
    },
    {
      "word": "ANURA",
      "description": "Zoological order comprising tailless amphibians such as frogs."
    },
    {
      "word": "BASEN",
      "description": "African hunting dog breed famous for not barking."
    },
    {
      "word": "BATIS",
      "description": "Small African songbird with contrasting black and white plumage."
    },
    {
      "word": "BETTA",
      "description": "Vibrantly colored Siamese fighting fish with ornate fins."
    },
    {
      "word": "BILBY",
      "description": "Desert-dwelling Australian marsupial with long silky ears."
    },
    {
      "word": "BITTN",
      "description": "Camouflaged marsh bird that freezes upright among reeds."
    },
    {
      "word": "BOUBU",
      "description": "African bushshrike singing synchronized duet melodies."
    },
    {
      "word": "BRANT",
      "description": "Small wild coastal sea goose with black head and neck."
    },
    {
      "word": "BURRO",
      "description": "Small domesticated donkey used as a sure-footed pack animal."
    },
    {
      "word": "CAIMN",
      "description": "Alligatorid croc native to Central and South America."
    },
    {
      "word": "CAPON",
      "description": "Domestic fowl specially fattened for culinary use."
    },
    {
      "word": "CARIB",
      "description": "North American wild reindeer migrating in vast herds."
    },
    {
      "word": "CHITA",
      "description": "Spotted African big cat specialized for explosive sprint speed."
    },
    {
      "word": "JAGUAR",
      "description": "Largest cat in the Americas with powerful crushing jaws."
    },
    {
      "word": "MONKEY",
      "description": "Agile primate with nimble hands and expressive social behavior."
    },
    {
      "word": "RABBIT",
      "description": "Small furry mammal with long ears and rapid reproduction."
    },
    {
      "word": "FALCON",
      "description": "Fastest animal on Earth capable of diving at over 200 mph."
    },
    {
      "word": "TURTLE",
      "description": "Reptile protected by a bony shell that retracts its head and limbs."
    },
    {
      "word": "LIZARD",
      "description": "Reptile with scaly skin, four legs, and movable eyelids."
    },
    {
      "word": "BEAVER",
      "description": "Nature's engineer constructing dams, canals, and river lodges."
    },
    {
      "word": "BADGER",
      "description": "Stout burrowing carnivore famous for fierce tenacity."
    },
    {
      "word": "FERRET",
      "description": "Slender domesticated mustelid known for playful curiosity."
    },
    {
      "word": "WEASEL",
      "description": "Small carnivorous mammal with a long slender body."
    },
    {
      "word": "WALRUS",
      "description": "Large flippered marine mammal with long ivory tusks."
    },
    {
      "word": "COUGAR",
      "description": "Powerful wild cat also known as mountain lion or puma."
    },
    {
      "word": "OCELOT",
      "description": "Small spotted wild cat native to tropical American forests."
    },
    {
      "word": "BABOON",
      "description": "Large Old World monkey with dog-like muzzle and social troops."
    },
    {
      "word": "GIBBON",
      "description": "Small acrobatic ape that swings through trees by brachiation."
    },
    {
      "word": "CONDOR",
      "description": "Massive New World vulture with an immense wingspan."
    },
    {
      "word": "PARROT",
      "description": "Colorful intelligent bird capable of mimicking human speech."
    },
    {
      "word": "TOUCAN",
      "description": "Tropical bird instantly recognized by its oversized colorful bill."
    },
    {
      "word": "SALMON",
      "description": "Anadromous fish that migrates upstream to spawn in rivers."
    },
    {
      "word": "MARLIN",
      "description": "Large apex billfish with an elongated spear-like snout."
    },
    {
      "word": "SHRIMP",
      "description": "Small decapod crustacean swimming in marine and freshwater."
    },
    {
      "word": "BEETLE",
      "description": "Diverse insect order with hardened protective wing cases."
    },
    {
      "word": "SPIDER",
      "description": "Eight-legged arachnid producing intricate silk webs."
    },
    {
      "word": "HORNET",
      "description": "Large aggressive social wasp building paper nests."
    },
    {
      "word": "CICADA",
      "description": "Loud insect known for high-pitched mating songs in summer."
    },
    {
      "word": "MANTIS",
      "description": "Carnivorous insect with grasping forelegs held in prayer."
    },
    {
      "word": "IGUANA",
      "description": "Herbivorous tropical lizard with a spiny crest along its back."
    },
    {
      "word": "PYTHON",
      "description": "Non-venomous constrictor snake that swallows prey whole."
    },
    {
      "word": "WOMBAT",
      "description": "Short-legged muscular Australian marsupial producing cube scat."
    },
    {
      "word": "POSSUM",
      "description": "Nocturnal tree-dwelling marsupial native to Australasia."
    },
    {
      "word": "GERBIL",
      "description": "Small desert rodent popular as an inquisitive gentle pet."
    },
    {
      "word": "GOPHER",
      "description": "Burrowing rodent creating extensive underground tunnel networks."
    },
    {
      "word": "MARMOT",
      "description": "Large ground squirrel hibernating in alpine mountain ranges."
    },
    {
      "word": "JACKAL",
      "description": "Opportunistic wild canine roaming savannahs and scrublands."
    },
    {
      "word": "COYOTE",
      "description": "Adaptable North American wild canine famous for nightly howls."
    },
    {
      "word": "SERVAL",
      "description": "Slender wild African cat with long legs and large radar ears."
    },
    {
      "word": "IMPALA",
      "description": "Graceful African antelope known for spectacular running leaps."
    },
    {
      "word": "ALPACA",
      "description": "Domesticated South American camelid bred for luxurious fleece."
    },
    {
      "word": "VICUNA",
      "description": "Wild Andean camelid producing the finest animal fiber on Earth."
    },
    {
      "word": "TENREC",
      "description": "Diverse insectivore endemic to Madagascar resembling hedgehogs."
    },
    {
      "word": "NUMBAT",
      "description": "Slender striped Australian marsupial feeding exclusively on termites."
    },
    {
      "word": "QUOLLS",
      "description": "Carnivorous spotted marsupial native to Australia and New Guinea."
    },
    {
      "word": "COATIS",
      "description": "Diurnal mammal with a long ringed tail held upright."
    },
    {
      "word": "GENETS",
      "description": "Slender cat-like carnivore with spotted coat and banded tail."
    },
    {
      "word": "CIVETS",
      "description": "Nocturnal mammal with spotted coat native to Asia and Africa."
    },
    {
      "word": "WALLAB",
      "description": "Medium-sized Australian marsupial closely related to kangaroos."
    },
    {
      "word": "DESMAN",
      "description": "Semi-aquatic insectivore related to moles with a flexible snout."
    },
    {
      "word": "SHREWS",
      "description": "Tiny hyperactive mammal with extremely fast metabolic rate."
    },
    {
      "word": "NUTRIA",
      "description": "Semi-aquatic rodent with bright orange teeth living in wetland burrows."
    },
    {
      "word": "DUGONG",
      "description": "Gentle marine mammal grazing on shallow underwater seagrass beds."
    },
    {
      "word": "AGOUTI",
      "description": "Tropical rodent essential for dispersing Brazil nut seeds."
    },
    {
      "word": "ALCOID",
      "description": "Pelagic seabird diving into ocean depths to capture schools of fish."
    },
    {
      "word": "ANOLIS",
      "description": "Small tree lizard with an expandable brightly colored throat fan."
    },
    {
      "word": "AVOCET",
      "description": "Slender wading bird with an elegant upturned bill."
    },
    {
      "word": "BABIRU",
      "description": "Sulawesi wild pig renowned for upward-curling tusk formations."
    },
    {
      "word": "BARBEL",
      "description": "Freshwater carp fish equipped with sensory facial barbels."
    },
    {
      "word": "BARBET",
      "description": "Plump tropical bird with heavy bristles around its bill."
    },
    {
      "word": "BASKET",
      "description": "Basket star echinoderm branching arms into dense filter nets."
    },
    {
      "word": "BELDEN",
      "description": "Alpine ground squirrel living in communal high-altitude colonies."
    },
    {
      "word": "BELUGA",
      "description": "Vocal arctic white whale nicknamed the sea canary."
    },
    {
      "word": "BICHIR",
      "description": "Ancient elongated African freshwater fish with primitive lungs."
    },
    {
      "word": "BITTER",
      "description": "Freshwater carp laying its eggs inside living river mussels."
    },
    {
      "word": "BLACKY",
      "description": "Blackbird species singing melodic dawn chorus songs."
    },
    {
      "word": "BLEAKS",
      "description": "Small silvery freshwater river fish gathering in dense shoals."
    },
    {
      "word": "BLENNY",
      "description": "Small elongated coastal fish perching on rocky tidal pools."
    },
    {
      "word": "BLOWFZ",
      "description": "Pufferfish that inflates its spiny body when threatened."
    },
    {
      "word": "BOBCAT",
      "description": "Medium-sized wild cat with tufted ears and spotted coat."
    },
    {
      "word": "BOBOWL",
      "description": "Small nocturnal owl species hunting insects across forest clearings."
    },
    {
      "word": "BONITO",
      "description": "Fast medium-sized predatory ocean fish in the mackerel family."
    },
    {
      "word": "BOOBYS",
      "description": "Seabird famous for bright blue feet and aerial plunge-dives."
    },
    {
      "word": "BRAMBL",
      "description": "Fringillid migratory finch breeding in dense northern taiga."
    },
    {
      "word": "BULLUL",
      "description": "Bulbul songbird celebrated for fluid musical whistles."
    },
    {
      "word": "BUNTIN",
      "description": "Small brightly colored seed-eating passerine songbird."
    },
    {
      "word": "BUZZRD",
      "description": "Broad-winged raptor soaring gracefully on thermal air currents."
    },
    {
      "word": "CAMBER",
      "description": "Camberwell butterfly with rich velvety purple-brown wings."
    },
    {
      "word": "CANARY",
      "description": "Small domesticated yellow songbird famed for vocal melodies."
    },
    {
      "word": "CANDIR",
      "description": "Tiny parasitic catfish native to the Amazon river basin."
    },
    {
      "word": "CAPELN",
      "description": "Small forage fish forming massive silver spawning shoals."
    },
    {
      "word": "CAPYBR",
      "description": "World's largest living rodent, thriving in South American wetlands."
    },
    {
      "word": "CARIBU",
      "description": "Migratory deer roaming Arctic tundra in expansive herds."
    },
    {
      "word": "CATFIS",
      "description": "Freshwater and marine fish with prominent sensory barbels."
    },
    {
      "word": "CHAFFN",
      "description": "Common European finch with pink breast and white wing bars."
    },
    {
      "word": "CHEVRO",
      "description": "Mouse-deer, the smallest hoofed mammal species in the world."
    },
    {
      "word": "CHIKOR",
      "description": "Eurasian game bird with bold black side flank stripes."
    },
    {
      "word": "CHOUGH",
      "description": "Crow-family mountain bird with curved bright red bill and legs."
    },
    {
      "word": "CISCOS",
      "description": "Deepwater whitefish swimming in cold northern glacial lakes."
    },
    {
      "word": "COCKAT",
      "description": "Small crested Australian parrot renowned for whistle tunes."
    },
    {
      "word": "CODLIN",
      "description": "Small marine cod fish grazing near kelp forest beds."
    },
    {
      "word": "COLIES",
      "description": "African mousebird with soft hair-like plumage and long tail."
    },
    {
      "word": "COOTES",
      "description": "Aquatic marsh bird swimming with lobed toes among lake reeds."
    }
  ],
  "food": [
    {
      "word": "CAKE",
      "description": "Sweet baked dessert typically frosted with icing."
    },
    {
      "word": "SOUP",
      "description": "Nutritious liquid food prepared by simmering ingredients in broth."
    },
    {
      "word": "RICE",
      "description": "Primary cereal grain feeding billions across the planet."
    },
    {
      "word": "MEAT",
      "description": "Protein-rich animal tissue consumed as food."
    },
    {
      "word": "FISH",
      "description": "Aquatic vertebrate harvested for delicious culinary dining."
    },
    {
      "word": "CORN",
      "description": "Cereal grain with golden kernels on a central cob."
    },
    {
      "word": "TACO",
      "description": "Traditional Mexican dish of folded tortilla with savory fillings."
    },
    {
      "word": "PLUM",
      "description": "Sweet juicy stone fruit with smooth purple or red skin."
    },
    {
      "word": "LIME",
      "description": "Zesty citrus fruit with vibrant green skin and sour juice."
    },
    {
      "word": "BEET",
      "description": "Earthy sweet root vegetable known for deep ruby color."
    },
    {
      "word": "LEEK",
      "description": "Culinary vegetable in the allium onion family with mild flavor."
    },
    {
      "word": "MINT",
      "description": "Aromatic herb imparting cool refreshing menthol flavor."
    },
    {
      "word": "SAGE",
      "description": "Woody aromatic herb with velvety leaves used in roasts."
    },
    {
      "word": "SALT",
      "description": "Essential crystalline mineral enhancing all culinary flavors."
    },
    {
      "word": "FIGS",
      "description": "Sweet pear-shaped fruit filled with crunchy edible seeds."
    },
    {
      "word": "PEAR",
      "description": "Juicy bell-shaped sweet fruit with crisp or melting flesh."
    },
    {
      "word": "PORK",
      "description": "Culinary meat from domestic swine prepared in savory cuts."
    },
    {
      "word": "BEEF",
      "description": "Culinary meat from cattle enjoyed in steaks and roasts."
    },
    {
      "word": "VEAL",
      "description": "Delicate tender meat from young dairy calves."
    },
    {
      "word": "LAMB",
      "description": "Tender succulent meat from young domestic sheep."
    },
    {
      "word": "TART",
      "description": "Baked open pastry crust filled with sweet fruit or savory custard."
    },
    {
      "word": "STEW",
      "description": "Hearty dish of meat and vegetables simmered slowly in gravy."
    },
    {
      "word": "CHIP",
      "description": "Crispy fried or baked thin slice of potato or corn."
    },
    {
      "word": "WRAP",
      "description": "Sandwich made with a soft flatbread rolled around fillings."
    },
    {
      "word": "SODA",
      "description": "Sweet carbonated beverage served chilled."
    },
    {
      "word": "MILK",
      "description": "Nutrient-rich liquid food produced by dairy mammals."
    },
    {
      "word": "CURD",
      "description": "Coagulated milk solids separated during cheese making."
    },
    {
      "word": "TOFU",
      "description": "Protein-packed curd made from coagulated soybean milk."
    },
    {
      "word": "HERB",
      "description": "Plant with aromatic leaves used for culinary seasoning."
    },
    {
      "word": "NUTS",
      "description": "Hard-shelled edible seed packed with healthy fats and protein."
    },
    {
      "word": "BEAN",
      "description": "Edible legume seed high in dietary fiber and plant protein."
    },
    {
      "word": "PEAS",
      "description": "Small spherical green seeds harvested from legume pods."
    },
    {
      "word": "KALE",
      "description": "Nutrient-dense dark green leafy cabbage vegetable."
    },
    {
      "word": "OKRA",
      "description": "Green pod vegetable celebrated for thickening gumbo soups."
    },
    {
      "word": "YAMS",
      "description": "Starchy edible tuber popular in West African and global cuisine."
    },
    {
      "word": "OATS",
      "description": "Cereal grain rolled or ground for hearty breakfast porridge."
    },
    {
      "word": "WINE",
      "description": "Fermented alcoholic beverage crafted from crushed grapes."
    },
    {
      "word": "FLAN",
      "description": "Sweet baked custard dessert with a caramel glaze."
    },
    {
      "word": "BRIE",
      "description": "Soft creamy French cheese with an edible white bloomy rind."
    },
    {
      "word": "PITA",
      "description": "Round pocket flatbread popular across Mediterranean cuisine."
    },
    {
      "word": "BREAD",
      "description": "Baked staple food made of flour, water, and yeast."
    },
    {
      "word": "PIZZA",
      "description": "Baked flat dough topped with tomato sauce, melted cheese, and toppings."
    },
    {
      "word": "SUSHI",
      "description": "Japanese dish of vinegared rice rolled with fresh seafood and seaweed."
    },
    {
      "word": "PASTA",
      "description": "Italian staple dough extruded into noodles, penne, or fusilli."
    },
    {
      "word": "SALAD",
      "description": "Dish of fresh raw greens, crisp vegetables, and savory dressing."
    },
    {
      "word": "STEAK",
      "description": "High-quality thick cut of prime beef grilled to perfection."
    },
    {
      "word": "APPLE",
      "description": "Crisp sweet pomaceous fruit enjoyed fresh, baked, or in cider."
    },
    {
      "word": "BERRY",
      "description": "Small fleshy juicy fruit packed with antioxidants and flavor."
    },
    {
      "word": "MANGO",
      "description": "Tropical stone fruit celebrated for luscious golden fragrant flesh."
    },
    {
      "word": "LEMON",
      "description": "Bright yellow citrus fruit known for bracing tartness and juice."
    },
    {
      "word": "MELON",
      "description": "Sweet large juicy fruit with thick rind, such as cantaloupe."
    },
    {
      "word": "PEACH",
      "description": "Velvety-skinned sweet stone fruit with juicy fragrant flesh."
    },
    {
      "word": "GRAPE",
      "description": "Small sweet spherical fruit growing in clusters on climbing vines."
    },
    {
      "word": "ONION",
      "description": "Aromatic bulb vegetable forming the savory base of world cooking."
    },
    {
      "word": "BACON",
      "description": "Cured pork belly sliced thin and crisped on a hot griddle."
    },
    {
      "word": "HONEY",
      "description": "Golden sweet nectar produced by industrious honeybees."
    },
    {
      "word": "SUGAR",
      "description": "Sweet crystalline carbohydrate extracted from cane or sugar beet."
    },
    {
      "word": "CREAM",
      "description": "Rich fatty dairy layer skimmed from fresh milk before churning."
    },
    {
      "word": "GRAVY",
      "description": "Savory sauce thickened from seasoned roasted meat pan juices."
    },
    {
      "word": "SAUCE",
      "description": "Liquid or semi-solid culinary accompaniment enhancing flavors."
    },
    {
      "word": "CURRY",
      "description": "Rich aromatic spiced stew originating in South Asian cuisine."
    },
    {
      "word": "CHILI",
      "description": "Hearty spicy stew of meat, beans, and fiery chili peppers."
    },
    {
      "word": "JELLY",
      "description": "Clear fruit spread prepared by cooking fruit juice with pectin."
    },
    {
      "word": "BAGEL",
      "description": "Ring-shaped yeast bread boiled before baking for a chewy crust."
    },
    {
      "word": "ROAST",
      "description": "Cut of seasoned meat or vegetables cooked in a dry oven."
    },
    {
      "word": "GOUDA",
      "description": "Mild yellow Dutch cheese made from whole cow's milk."
    },
    {
      "word": "BASIL",
      "description": "Aromatic herb of the mint family, hero of Italian pesto."
    },
    {
      "word": "THYME",
      "description": "Woody culinary herb with tiny fragrant leaves used in braises."
    },
    {
      "word": "CUMIN",
      "description": "Warm earthy spice essential in curries, tacos, and rubs."
    },
    {
      "word": "CLOVE",
      "description": "Aromatic dried flower bud of an Indonesian tropical tree."
    },
    {
      "word": "COCOA",
      "description": "Powder made from roasted ground cacao beans, heart of chocolate."
    },
    {
      "word": "FUDGE",
      "description": "Rich soft confection made of sugar, butter, and milk or cocoa."
    },
    {
      "word": "CANDY",
      "description": "Sweet confection made concentrated with sugar or syrup."
    },
    {
      "word": "DONUT",
      "description": "Ring of sweetened fried dough glazed or dusted with sugar."
    },
    {
      "word": "CREPE",
      "description": "Thin delicate French pancake folded around sweet or savory fillings."
    },
    {
      "word": "WAFER",
      "description": "Thin crisp light biscuit often layered with sweet cream filling."
    },
    {
      "word": "OLIVE",
      "description": "Small oval fruit cured for savory table snacks or cold-pressed oil."
    },
    {
      "word": "GUAVA",
      "description": "Tropical fruit with sweet pink flesh and high vitamin C."
    },
    {
      "word": "RAMEN",
      "description": "Japanese noodle soup served in rich broth with savory toppings."
    },
    {
      "word": "BROTH",
      "description": "Savory liquid strained from simmering meat, bones, or vegetables."
    },
    {
      "word": "PILAF",
      "description": "Fluffy seasoned rice cooked in aromatic broth with spices."
    },
    {
      "word": "SALSA",
      "description": "Zesty Mexican condiment made of chopped tomatoes, onions, and chiles."
    },
    {
      "word": "PESTO",
      "description": "Genoese green sauce crushed from fresh basil, pine nuts, and cheese."
    },
    {
      "word": "AIOLI",
      "description": "Creamy Proven\u00e7al emulsion of garlic, olive oil, and egg yolk."
    },
    {
      "word": "SYRUP",
      "description": "Thick sweet liquid boiled down from tree sap or fruit juices."
    },
    {
      "word": "CIDER",
      "description": "Refreshing beverage fermented or pressed from fresh autumn apples."
    },
    {
      "word": "LATTE",
      "description": "Espresso coffee topped with steamed milk and delicate foam."
    },
    {
      "word": "MOCHA",
      "description": "Decadent blend of espresso, steamed milk, and rich chocolate."
    },
    {
      "word": "POUND",
      "description": "Dense rich butter pound cake seasoned with vanilla."
    },
    {
      "word": "SCONE",
      "description": "British baked quick bread served with clotted cream and jam."
    },
    {
      "word": "TOAST",
      "description": "Sliced bread browned and crisped by exposure to radiant heat."
    },
    {
      "word": "CRUST",
      "description": "The golden outer crisp layer of baked artisan breads or pies."
    },
    {
      "word": "YEAST",
      "description": "Microscopic single-celled fungus fermenting sugars to leaven bread."
    },
    {
      "word": "GRAIN",
      "description": "Small hard edible seed harvested from cultivated cereal grasses."
    },
    {
      "word": "WHEAT",
      "description": "Major cereal grain milled into flour for global bread making."
    },
    {
      "word": "FLOUR",
      "description": "Finely ground powder made by milling cereal grains or roots."
    },
    {
      "word": "SPICE",
      "description": "Aromatic dried seed, bark, or root used to season cuisines."
    },
    {
      "word": "POACH",
      "description": "Gentle cooking method simmering food in liquid below boiling."
    },
    {
      "word": "ANCHO",
      "description": "Mild dried poblano chili pepper with rich raisin sweetness."
    },
    {
      "word": "SAUTE",
      "description": "Fast cooking method frying ingredients in a small amount of hot fat."
    },
    {
      "word": "GRILL",
      "description": "Cooking food over direct open flame on a metal grate."
    },
    {
      "word": "BROIL",
      "description": "Cooking food by exposing it to intense direct overhead heat."
    },
    {
      "word": "SMOKE",
      "description": "Flavoring and curing meats over smoldering aromatic wood fires."
    },
    {
      "word": "BRINE",
      "description": "Concentrated saltwater solution used for pickling and curing foods."
    },
    {
      "word": "CRISP",
      "description": "Pleasantly firm and easily broken baked food texture."
    },
    {
      "word": "JUICY",
      "description": "Full of natural flavorful liquid and moisture."
    },
    {
      "word": "SWEET",
      "description": "Pleasing sugary taste characteristic of honey and ripe fruit."
    },
    {
      "word": "SALTY",
      "description": "Savory flavor profile imparted by natural sea minerals."
    },
    {
      "word": "PECAN",
      "description": "Sweet buttery nut native to the southern United States."
    },
    {
      "word": "ACORN",
      "description": "Nut of the oak tree traditionally leached and ground into flour."
    },
    {
      "word": "BURGER",
      "description": "Juicy ground meat patty grilled and served inside a soft bun."
    },
    {
      "word": "CHEESE",
      "description": "Nutrient-rich dairy food crafted from coagulated milk curds."
    },
    {
      "word": "WAFFLE",
      "description": "Crisp batter cake baked in an indented grid pattern iron."
    },
    {
      "word": "MUFFIN",
      "description": "Individual cup-shaped baked quick bread, often with blueberries."
    },
    {
      "word": "COOKIE",
      "description": "Sweet small flat baked treat containing chocolate chips or nuts."
    },
    {
      "word": "BUTTER",
      "description": "Rich yellow dairy spread churned from fresh heavy cream."
    },
    {
      "word": "YOGURT",
      "description": "Creamy fermented dairy food cultured with beneficial probiotics."
    },
    {
      "word": "NOODLE",
      "description": "Long thin strip of pasta dough boiled in broths and sauces."
    },
    {
      "word": "POTATO",
      "description": "Versatile starchy tuber enjoyed mashed, roasted, or fried."
    },
    {
      "word": "TOMATO",
      "description": "Juicy red fruit culinarily celebrated in savory sauces and salads."
    },
    {
      "word": "CARROT",
      "description": "Sweet crunchy orange root vegetable packed with beta carotene."
    },
    {
      "word": "GARLIC",
      "description": "Pungent allium bulb cloves essential across world cuisines."
    },
    {
      "word": "PEPPER",
      "description": "Pungent spice from dried peppercorns or crisp sweet bell pepper."
    },
    {
      "word": "GINGER",
      "description": "Spicy aromatic rhizome adding warmth to curries and teas."
    },
    {
      "word": "BANANA",
      "description": "Elongated tropical yellow fruit rich in potassium and energy."
    },
    {
      "word": "CHERRY",
      "description": "Small round deep-red stone fruit loved fresh or in pies."
    },
    {
      "word": "ORANGE",
      "description": "Sweet round citrus fruit celebrated for juicy breakfast juice."
    },
    {
      "word": "PAPAYA",
      "description": "Tropical melon-like fruit with sweet salmon-pink flesh."
    },
    {
      "word": "OYSTER",
      "description": "Bivalve marine mollusk prized fresh on the half shell."
    },
    {
      "word": "BISCOT",
      "description": "Twice-baked crunchy Italian almond cookie dipped in espresso."
    },
    {
      "word": "PASTRY",
      "description": "Flaky baked dough made of flour, butter, and water."
    },
    {
      "word": "SUNDAE",
      "description": "Ice cream dessert topped with fudge sauce, whipped cream, and nuts."
    },
    {
      "word": "SORBET",
      "description": "Refreshing frozen dessert made of fruit puree, sugar, and water."
    },
    {
      "word": "GELATO",
      "description": "Silky dense Italian ice cream churned with less air."
    },
    {
      "word": "ECLAIR",
      "description": "Oblong choux pastry filled with cream and topped with chocolate glaze."
    },
    {
      "word": "OMELET",
      "description": "Fluffy beaten eggs cooked and folded over cheese or vegetables."
    },
    {
      "word": "FONDUE",
      "description": "Swiss melted cheese pot in which bread cubes are dipped."
    },
    {
      "word": "HUMMUS",
      "description": "Creamy Middle Eastern dip blended from chickpeas, tahini, and lemon."
    },
    {
      "word": "PAELLA",
      "description": "Famous Spanish saffron rice dish cooked in a wide shallow pan."
    },
    {
      "word": "RISOTT",
      "description": "Creamy Northern Italian rice dish stirred constantly with broth."
    },
    {
      "word": "QUICHE",
      "description": "Savory French tart filled with baked egg custard, cheese, and meats."
    },
    {
      "word": "TAMALE",
      "description": "Mesoamerican corn masa dough steamed in a corn husk wrapper."
    },
    {
      "word": "CREPES",
      "description": "Thin delicate pancakes folded with sweet chocolate or fruit."
    },
    {
      "word": "PANINI",
      "description": "Italian pressed toasted sandwich grilled between ribbed plates."
    },
    {
      "word": "BAGELS",
      "description": "Chewy ring-shaped bread rolls topped with poppy or sesame seeds."
    },
    {
      "word": "SCONES",
      "description": "Traditional British afternoon tea quick breads served with jam."
    },
    {
      "word": "TARTES",
      "description": "Open-faced French fruit pastries with delicate butter crusts."
    },
    {
      "word": "PICKLE",
      "description": "Cucumber or vegetable preserved and fermented in tangy brine."
    },
    {
      "word": "RELISH",
      "description": "Cooked and pickled chopped vegetable condiment."
    },
    {
      "word": "KETCHP",
      "description": "Sweet and tangy condiment sauce crafted from ripe tomatoes."
    },
    {
      "word": "MUSTAR",
      "description": "Pungent yellow or brown condiment prepared from mustard seeds."
    },
    {
      "word": "WASABI",
      "description": "Intense green Japanese horseradish paste served with fresh sushi."
    },
    {
      "word": "NUTMEG",
      "description": "Warm aromatic spice grated from the seed of a tropical evergreen tree."
    },
    {
      "word": "SESAME",
      "description": "Tiny oil-rich seeds sprinkled over baked breads and burger buns."
    },
    {
      "word": "WALNUT",
      "description": "Wrinkled tree nut renowned for rich flavor and brain-boosting fats."
    },
    {
      "word": "ALMOND",
      "description": "Nutritious sweet tree nut enjoyed roasted, sliced, or as milk."
    },
    {
      "word": "PEANUT",
      "description": "Underground edible legume pod ground into creamy sandwich butter."
    },
    {
      "word": "CASHEW",
      "description": "Crescent-shaped sweet buttery nut harvested from tropical trees."
    },
    {
      "word": "COCONU",
      "description": "Large tropical palm nut providing refreshing water, milk, and oil."
    },
    {
      "word": "CELERY",
      "description": "Crisp fibrous green stalk vegetable with high water content."
    },
    {
      "word": "RADISH",
      "description": "Crisp peppery root vegetable eaten raw in fresh salads."
    },
    {
      "word": "SPINAC",
      "description": "Tender dark green leafy vegetable packed with iron and nutrients."
    },
    {
      "word": "SQUASH",
      "description": "Hearty edible gourd family vegetable roasted in autumn dishes."
    },
    {
      "word": "TURNIP",
      "description": "Round white and purple root vegetable roasted in winter stews."
    },
    {
      "word": "PARSNP",
      "description": "Sweet cream-colored root vegetable closely related to carrots."
    },
    {
      "word": "LENTIL",
      "description": "High-protein small lens-shaped legume cooked in hearty soups."
    },
    {
      "word": "SIRLOI",
      "description": "Prime flavorful cut of beef steak taken from the lower back."
    },
    {
      "word": "RIBEYE",
      "description": "Highly marbled beef steak celebrated for rich juicy tenderness."
    },
    {
      "word": "BRISKT",
      "description": "Tough cut of beef breast slow-smoked for hours to melting texture."
    },
    {
      "word": "SAUSAG",
      "description": "Seasoned minced meat encased in a cylindrical skin."
    },
    {
      "word": "SALAMI",
      "description": "Dry-cured fermented sausage seasoned with garlic and wine."
    },
    {
      "word": "CHICKN",
      "description": "Popular poultry meat roasted, fried, or stewed worldwide."
    },
    {
      "word": "TURKEY",
      "description": "Large poultry bird roasted whole as centerpiece holiday meal."
    },
    {
      "word": "MUTTON",
      "description": "Meat of an adult domestic sheep with robust hearty flavor."
    },
    {
      "word": "VENISN",
      "description": "Lean savory game meat harvested from wild deer."
    },
    {
      "word": "TROUTZ",
      "description": "Freshwater rainbow game fish cooked in brown butter with almonds."
    },
    {
      "word": "TILAPI",
      "description": "Mild white freshwater fish farmed worldwide."
    },
    {
      "word": "HADDOK",
      "description": "Flaky Atlantic whitefish traditional in British fish and chips."
    },
    {
      "word": "HALIBT",
      "description": "Large flatfish with firm snowy-white sweet flesh."
    },
    {
      "word": "CAVIAR",
      "description": "Salt-cured sturgeon roe delicacy served chilled with champagne."
    },
    {
      "word": "SCALLP",
      "description": "Tender sweet marine bivalve mollusk seared golden in hot butter."
    },
    {
      "word": "MUSSEL",
      "description": "Dark-shelled marine bivalve steamed in white wine and garlic."
    },
    {
      "word": "CLAMSZ",
      "description": "Edible burrowing bivalve mollusks simmered into hearty chowders."
    },
    {
      "word": "CALMAR",
      "description": "Mediterranean squid rings tossed in seasoned flour and fried crisp."
    },
    {
      "word": "CANDYS",
      "description": "Colorful confectionery sweets made of crystallized sugar syrups."
    },
    {
      "word": "CARAML",
      "description": "Rich sweet confection produced by heating and browning sugars."
    },
    {
      "word": "TOFFEE",
      "description": "Hard chewy candy made by caramelizing sugar with golden butter."
    },
    {
      "word": "PRALIN",
      "description": "Confection made of whole pecans or almonds coated in caramelized sugar."
    },
    {
      "word": "TRUFFL",
      "description": "Rich chocolate ganache ball coated in cocoa or luxurious fungal tuber."
    },
    {
      "word": "MARSHM",
      "description": "Fluffy spongy confectionery treat roasted golden over campfires."
    },
    {
      "word": "CIDERZ",
      "description": "Warm spiced apple cider steeped with cinnamon sticks and cloves."
    },
    {
      "word": "LIQUEU",
      "description": "Sweet alcoholic beverage infused with herbs, fruits, or cream."
    },
    {
      "word": "TEASPO",
      "description": "Small spoon used for stirring tea and precise cooking measurements."
    },
    {
      "word": "CHOPST",
      "description": "Pair of tapered eating utensils traditional in East Asian dining."
    },
    {
      "word": "ANANAS",
      "description": "Tropical pineapple fruit celebrated for sweet juicy yellow slices."
    },
    {
      "word": "AVOCAD",
      "description": "Rich creamy green fruit high in heart-healthy monounsaturated fats."
    },
    {
      "word": "BARLEY",
      "description": "Nutritious cereal grain used in hearty soups and brewing malts."
    },
    {
      "word": "BEETRT",
      "description": "Sweet red beet root roasted or pickled for earthy depth."
    },
    {
      "word": "GRAHAM",
      "description": "Coarsely ground whole wheat flour or sweet honey crackers."
    },
    {
      "word": "CREAMS",
      "description": "Rich whipped dairy creams served atop desserts."
    }
  ],
  "sports": [
    {
      "word": "BALL",
      "description": "Spherical object kicked, thrown, or hit in countless sports."
    },
    {
      "word": "GOAL",
      "description": "Target structure into which players score points."
    },
    {
      "word": "SWIM",
      "description": "Propelling the body through water via synchronized strokes."
    },
    {
      "word": "RACE",
      "description": "Speed competition to determine the fastest runner or vehicle."
    },
    {
      "word": "SURF",
      "description": "Riding breaking ocean waves on a sleek buoyant board."
    },
    {
      "word": "JUMP",
      "description": "Propelling oneself upward or across distance into the air."
    },
    {
      "word": "DIVE",
      "description": "Acrobatic plunge into water headfirst from a high platform."
    },
    {
      "word": "POLO",
      "description": "Team ball game played on horseback with long-handled mallets."
    },
    {
      "word": "JUDO",
      "description": "Japanese martial art focusing on throws and joint locks."
    },
    {
      "word": "LIFT",
      "description": "Hoisting heavy barbell weights overhead in Olympic competition."
    },
    {
      "word": "PUNT",
      "description": "Kicking a football dropped from hands before it hits the ground."
    },
    {
      "word": "FOUL",
      "description": "Violation of game rules resulting in penalty or free throws."
    },
    {
      "word": "BASE",
      "description": "One of the four stations a baseball runner must touch."
    },
    {
      "word": "PASS",
      "description": "Transferring the ball to a teammate across the field."
    },
    {
      "word": "KICK",
      "description": "Striking a ball forcefully with the foot."
    },
    {
      "word": "DUNK",
      "description": "Leaping and slamming a basketball forcefully through the hoop."
    },
    {
      "word": "SHOT",
      "description": "Attempt to score a goal or basket during play."
    },
    {
      "word": "TEAM",
      "description": "Coordinated group of athletes competing together."
    },
    {
      "word": "CLUB",
      "description": "Specialized stick used to strike golf balls toward holes."
    },
    {
      "word": "PUCK",
      "description": "Hard vulcanized rubber disk used in ice hockey."
    },
    {
      "word": "MATS",
      "description": "Padded floor surfaces protecting gymnasts and wrestlers."
    },
    {
      "word": "CREW",
      "description": "Rowing team synchronized in rowing a slender racing shell."
    },
    {
      "word": "RUNS",
      "description": "Points scored in baseball or cricket by crossing bases."
    },
    {
      "word": "LAPS",
      "description": "One complete circuit around a running track or pool."
    },
    {
      "word": "NETS",
      "description": "Meshed barrier dividing court in tennis and volleyball."
    },
    {
      "word": "HOOP",
      "description": "Circular metal rim with hanging net in basketball."
    },
    {
      "word": "BATS",
      "description": "Wooden or metal club used to hit pitched baseballs."
    },
    {
      "word": "PADS",
      "description": "Protective equipment worn on knees, shins, and shoulders."
    },
    {
      "word": "HELM",
      "description": "Tiller or wheel steering a high-speed racing sailboat."
    },
    {
      "word": "PULL",
      "description": "Rowing stroke or curling stone delivery motion."
    },
    {
      "word": "PUSH",
      "description": "Forward thrusting motion in weightlifting or scrum."
    },
    {
      "word": "SPIN",
      "description": "Rotational torque applied to a ball to bend its trajectory."
    },
    {
      "word": "DUEL",
      "description": "One-on-one athletic contest between fencing or tennis rivals."
    },
    {
      "word": "TOUR",
      "description": "Major tournament circuit such as PGA or cycling Tour de France."
    },
    {
      "word": "WALK",
      "description": "Advancing to first base on four called balls in baseball."
    },
    {
      "word": "DART",
      "description": "Pointed projectile thrown at a circular numbered dartboard."
    },
    {
      "word": "ROPE",
      "description": "Skipping rope used for cardio conditioning and footwork."
    },
    {
      "word": "RINK",
      "description": "Enclosed ice sheet designed for figure skating and hockey."
    },
    {
      "word": "VAUT",
      "description": "Gymnastic apparatus leaped over with explosive spring."
    },
    {
      "word": "PUMP",
      "description": "Rhythmic body movement generating speed on a skateboard ramp."
    },
    {
      "word": "RUGBY",
      "description": "High-intensity contact team sport played with an oval ball."
    },
    {
      "word": "CHESS",
      "description": "Ancient strategic board game played across 64 squares."
    },
    {
      "word": "TRACK",
      "description": "Running oval venue for sprints, hurdles, and relays."
    },
    {
      "word": "FIELD",
      "description": "Grassy playing surface for soccer, football, and baseball."
    },
    {
      "word": "COURT",
      "description": "Designated hardwood or clay area for basketball and tennis."
    },
    {
      "word": "SCORE",
      "description": "Points tally accumulated by athletes during a contest."
    },
    {
      "word": "PITCH",
      "description": "Playing ground for cricket and soccer, or throwing a baseball."
    },
    {
      "word": "SERVE",
      "description": "Initial stroke putting the ball into play in tennis or volleyball."
    },
    {
      "word": "MATCH",
      "description": "Head-to-head competition between opposing players or teams."
    },
    {
      "word": "SKATE",
      "description": "Boot with metal blade or wheels for gliding over ice or pavement."
    },
    {
      "word": "VAULT",
      "description": "Gymnastic apparatus vaulted over with speed and rotation."
    },
    {
      "word": "COACH",
      "description": "Tactical mentor guiding athletes in strategy and conditioning."
    },
    {
      "word": "GUARD",
      "description": "Defensive position protecting the basket or quarterback."
    },
    {
      "word": "SPIKE",
      "description": "Hard downward smash of the volleyball over the net."
    },
    {
      "word": "RELAY",
      "description": "Team race where runners pass a baton around the track."
    },
    {
      "word": "BOXER",
      "description": "Combat athlete competing with gloved punches in a ring."
    },
    {
      "word": "ROWER",
      "description": "Athlete pulling oars to propel a racing shell over water."
    },
    {
      "word": "RIDER",
      "description": "Equestrian athlete jumping hurdles on horseback."
    },
    {
      "word": "PILOT",
      "description": "Motorsport driver steering high-downforce racing cars."
    },
    {
      "word": "MEDAL",
      "description": "Gold, silver, or bronze award earned on Olympic podiums."
    },
    {
      "word": "SWING",
      "description": "Fluid pendulum motion striking a golf ball or baseball."
    },
    {
      "word": "SPEED",
      "description": "Velocity and rapid pace exhibited by elite sprinters."
    },
    {
      "word": "POWER",
      "description": "Explosive athletic strength combined with swift velocity."
    },
    {
      "word": "SLIDE",
      "description": "Feet-first dive onto base to avoid a tag in baseball."
    },
    {
      "word": "TACKL",
      "description": "Defensive move bringing an opponent to the turf."
    },
    {
      "word": "PUNCH",
      "description": "Forceful strike delivered by fists in combat sports."
    },
    {
      "word": "BLOCK",
      "description": "Defensive stop preventing an opponent shot or pass."
    },
    {
      "word": "CATCH",
      "description": "Securing a thrown ball firmly in hands or leather glove."
    },
    {
      "word": "THROW",
      "description": "Propelling a ball, javelin, or discus across distance."
    },
    {
      "word": "SPRNT",
      "description": "Maximum effort short-distance dash at explosive speed."
    },
    {
      "word": "DRIBL",
      "description": "Bouncing a basketball or tapping a soccer ball on the move."
    },
    {
      "word": "DRIVE",
      "description": "Powerful long-distance tee shot in golf or charge to the rim."
    },
    {
      "word": "PUTTS",
      "description": "Gentle precision golf strokes rolling the ball into the cup."
    },
    {
      "word": "CHIPS",
      "description": "Short lofted golf approach shots landing softly near the pin."
    },
    {
      "word": "GLOVE",
      "description": "Padded leather mitt protecting hands in baseball and boxing."
    },
    {
      "word": "CLEAT",
      "description": "Spiked shoe sole providing traction on turf and grass fields."
    },
    {
      "word": "SHIRT",
      "description": "Athletic jersey displaying team colors and player numbers."
    },
    {
      "word": "TIMER",
      "description": "Electronic clock recording race times to the millisecond."
    },
    {
      "word": "FINAL",
      "description": "Championship showdown determining the tournament victor."
    },
    {
      "word": "ROUND",
      "description": "Timed division of a boxing bout or 18 holes of golf."
    },
    {
      "word": "DERBY",
      "description": "Intense local rivalry match between two neighboring teams."
    },
    {
      "word": "ARENA",
      "description": "Enclosed indoor stadium hosting basketball and ice hockey."
    },
    {
      "word": "STAND",
      "description": "Tiered seating rows where passionate fans cheer on teams."
    },
    {
      "word": "SQUAD",
      "description": "Roster of athletes selected to represent a team or nation."
    },
    {
      "word": "CROWD",
      "description": "Thousands of cheering spectators creating stadium energy."
    },
    {
      "word": "CHEER",
      "description": "Vocal encouragement shouted by fans to inspire athletes."
    },
    {
      "word": "BOOST",
      "description": "Sudden burst of speed or stamina during a race."
    },
    {
      "word": "SWEEP",
      "description": "Brushing the ice in front of a curling stone, or winning all games."
    },
    {
      "word": "SPLIT",
      "description": "Intermediate race lap time benchmark or bowling pin split."
    },
    {
      "word": "SPARE",
      "description": "Knocking down remaining bowling pins on the second roll."
    },
    {
      "word": "CLIMB",
      "description": "Scaling sheer rock walls or artificial climbing gym routes."
    },
    {
      "word": "CANOE",
      "description": "Narrow watercraft paddled through white-water rapids."
    },
    {
      "word": "KAYAK",
      "description": "Enclosed watercraft propelled with a double-bladed paddle."
    },
    {
      "word": "YACHT",
      "description": "Sleek sailing vessel racing in competitive regattas."
    },
    {
      "word": "SURFR",
      "description": "Wave rider performing aerial carves on ocean surfboards."
    },
    {
      "word": "SKIER",
      "description": "Athlete carving down snow-covered alpine mountain pistes."
    },
    {
      "word": "DRAFT",
      "description": "Riding in an opponent's aerodynamic slipstream to conserve energy."
    },
    {
      "word": "RACER",
      "description": "Competitor racing against opponents and clocks."
    },
    {
      "word": "PACER",
      "description": "Athlete setting a steady target rhythm in marathon races."
    },
    {
      "word": "BOARD",
      "description": "Surfboard, snowboard, or skateboard ridden across terrain."
    },
    {
      "word": "RINGS",
      "description": "Gymnastic apparatus consisting of two suspended wooden rings."
    },
    {
      "word": "BEAMS",
      "description": "Narrow 4-inch wide balance beam walked and flipped upon."
    },
    {
      "word": "TRAPS",
      "description": "Clay targets launched into the air for shotgun trap shooting."
    },
    {
      "word": "TAEKW",
      "description": "Korean martial art characterized by head-height leaping kicks."
    },
    {
      "word": "AIKID",
      "description": "Japanese martial art neutralizing opponents by redirecting energy."
    },
    {
      "word": "SUMOZ",
      "description": "Traditional Japanese wrestling where rikishi push opponents out of ring."
    },
    {
      "word": "KENDO",
      "description": "Japanese martial art of bamboo sword fencing in protective armor."
    },
    {
      "word": "TOWEL",
      "description": "Absorbent cloth used to wipe sweat between sets."
    },
    {
      "word": "LANES",
      "description": "Designated swimming or bowling corridors."
    },
    {
      "word": "TRAMP",
      "description": "Trampoline used in artistic gymnastics routines."
    },
    {
      "word": "SOCCER",
      "description": "World's most popular team ball game played on a grass pitch."
    },
    {
      "word": "TENNIS",
      "description": "Racket sport played singles or doubles over a central net."
    },
    {
      "word": "BOXING",
      "description": "Combat sport where two athletes spar with gloved punches in a ring."
    },
    {
      "word": "ROWING",
      "description": "Water sport where crews propel boats with synchronized oars."
    },
    {
      "word": "SKIING",
      "description": "Gliding down snow-covered mountain slopes on slender skis."
    },
    {
      "word": "HOCKEY",
      "description": "Fast-paced team sport played on ice with sticks and a rubber puck."
    },
    {
      "word": "KARATE",
      "description": "Japanese martial art emphasizing striking, kicking, and kata."
    },
    {
      "word": "SPORTS",
      "description": "Athletic games and competitive physical pastimes."
    },
    {
      "word": "ARCHER",
      "description": "Athlete shooting precision arrows at a concentric target."
    },
    {
      "word": "SPRINT",
      "description": "Full-speed dash over 100 or 200 meters on a rubber track."
    },
    {
      "word": "HURDLE",
      "description": "Barrier leaped over at full speed during track hurdle races."
    },
    {
      "word": "DISCUS",
      "description": "Heavy circular lens-shaped disk thrown for distance in field events."
    },
    {
      "word": "RUNNER",
      "description": "Athlete competing in middle-distance or marathon road races."
    },
    {
      "word": "JOCKEY",
      "description": "Professional equestrian riding thoroughbred horses in races."
    },
    {
      "word": "UMPIRE",
      "description": "Official calling balls and strikes in baseball or tennis points."
    },
    {
      "word": "LEAGUE",
      "description": "Association of sports teams competing for a season trophy."
    },
    {
      "word": "MEDALS",
      "description": "Gold, silver, and bronze podium awards presented to winners."
    },
    {
      "word": "PODIUM",
      "description": "Three-tiered platform where medalists stand for anthems."
    },
    {
      "word": "HELMET",
      "description": "Hard protective headgear worn in cycling, football, and hockey."
    },
    {
      "word": "JERSEY",
      "description": "Team uniform shirt bearing squad colors and squad crest."
    },
    {
      "word": "SHORTS",
      "description": "Lightweight athletic bottoms worn for running and basketball."
    },
    {
      "word": "CLEATS",
      "description": "Specialized shoes with molded studs for traction on grass."
    },
    {
      "word": "RACKET",
      "description": "Strung frame used to strike tennis and badminton shuttlecocks."
    },
    {
      "word": "BATTER",
      "description": "Baseball player standing in the batter's box facing pitches."
    },
    {
      "word": "PITCHR",
      "description": "Baseball player throwing the ball toward the strike zone."
    },
    {
      "word": "CATCHR",
      "description": "Baseball player crouching behind home plate in gear."
    },
    {
      "word": "STRIKR",
      "description": "Soccer attacking player whose primary objective is scoring."
    },
    {
      "word": "KEEPER",
      "description": "Goalkeeper guarding the goalmouth against opposing shots."
    },
    {
      "word": "DEFEND",
      "description": "Stopping an opponent from scoring points or advancing the ball."
    },
    {
      "word": "ATTACK",
      "description": "Coordinated offensive push toward the opposing goal."
    },
    {
      "word": "SLALOM",
      "description": "Zigzag downhill skiing race between closely spaced gate poles."
    },
    {
      "word": "VELODR",
      "description": "Indoor banked oval track for high-speed track cycling."
    },
    {
      "word": "PADDLE",
      "description": "Short oar used to propel kayaks, canoes, and dragon boats."
    },
    {
      "word": "WICKET",
      "description": "Three wooden stumps topped by bails defended in cricket."
    },
    {
      "word": "BOWLNG",
      "description": "Rolling a heavy ball to knock down ten pins at alley end."
    },
    {
      "word": "FINISH",
      "description": "The line or banner marking the end of a race."
    },
    {
      "word": "VICTOR",
      "description": "Triumphant champion winning the contest or championship."
    },
    {
      "word": "CHAMPN",
      "description": "Title holder crowned winner of a tournament or division."
    },
    {
      "word": "RECORD",
      "description": "Fastest time or greatest distance ever recorded in competition."
    },
    {
      "word": "STREAK",
      "description": "Consecutive string of game victories without a defeat."
    },
    {
      "word": "INNING",
      "description": "Division of a baseball or cricket game where teams alternate."
    },
    {
      "word": "QUARTR",
      "description": "One of four periods in basketball and American football."
    },
    {
      "word": "WHISTL",
      "description": "High-pitched tool blown by referee to start and halt play."
    },
    {
      "word": "TACKLE",
      "description": "Seizing and bringing down an opponent holding the ball."
    },
    {
      "word": "VOLLEY",
      "description": "Hitting a ball before it bounces on the court surface."
    },
    {
      "word": "SMASHD",
      "description": "Powerful high-velocity overhead smash in badminton or tennis."
    },
    {
      "word": "DRIVER",
      "description": "Longest club in golf bag designed for maximum distance tee shots."
    },
    {
      "word": "PUTTER",
      "description": "Flat-faced golf club used on greens for precision rolling."
    },
    {
      "word": "FAIRWY",
      "description": "Closely mown grass corridor between golf tee and putting green."
    },
    {
      "word": "BUNKER",
      "description": "Sand hazard obstacle on golf courses challenging approach shots."
    },
    {
      "word": "BIRDIE",
      "description": "Score of one stroke under par on an individual golf hole."
    },
    {
      "word": "EAGLES",
      "description": "Score of two strokes under par on an individual golf hole."
    },
    {
      "word": "BOOGIE",
      "description": "Score of one stroke over par on an individual golf hole."
    },
    {
      "word": "BALLER",
      "description": "Skilled basketball player renowned for exceptional court play."
    },
    {
      "word": "CORNER",
      "description": "Free kick taken from field corner in soccer when ball goes out."
    },
    {
      "word": "OFFSID",
      "description": "Illegal position ahead of the second-last defender in soccer."
    },
    {
      "word": "REDCAR",
      "description": "Ejection card shown by referee expelling a player from match."
    },
    {
      "word": "SCORER",
      "description": "Player who puts the ball or puck into the net for a point."
    },
    {
      "word": "ASSIST",
      "description": "Pass directly leading to a scored goal or basketball basket."
    },
    {
      "word": "REBOUN",
      "description": "Gaining possession of the basketball after a missed shot."
    },
    {
      "word": "BLOCKS",
      "description": "Defensive swatting away of an opponent's shot attempts."
    },
    {
      "word": "STEALS",
      "description": "Taking the ball away from a dribbling or passing opponent."
    },
    {
      "word": "FAULSZ",
      "description": "Illegal contacts resulting in referee whistle and penalty."
    },
    {
      "word": "PENALT",
      "description": "Spot kick awarded for foul committed inside the penalty area."
    },
    {
      "word": "CHALLN",
      "description": "Video review request challenging an on-field referee call."
    },
    {
      "word": "SEASON",
      "description": "Yearly schedule of regular games culminating in playoffs."
    },
    {
      "word": "PLAYOF",
      "description": "Postseason elimination tournament determining champions."
    },
    {
      "word": "WARMUP",
      "description": "Pre-game stretching and drills preparing athlete muscles."
    },
    {
      "word": "STRETB",
      "description": "Flexibility exercises increasing muscle range of motion."
    },
    {
      "word": "FITNES",
      "description": "Physical condition of athletic stamina, strength, and agility."
    },
    {
      "word": "STAMIN",
      "description": "Endurance capacity to maintain high performance over time."
    },
    {
      "word": "AGILTY",
      "description": "Ability to change direction rapidly with balance and control."
    },
    {
      "word": "TACTIC",
      "description": "Strategic game plan executed by coach and squad to win."
    },
    {
      "word": "MENTOR",
      "description": "Experienced veteran athlete guiding young developing players."
    },
    {
      "word": "MASCOT",
      "description": "Costumed character entertaining stadium fans during breaks."
    },
    {
      "word": "ARENAS",
      "description": "Large modern indoor sports stadium complexes hosting crowds."
    },
    {
      "word": "PULLUP",
      "description": "Upper body strength exercise raising chin over a bar."
    },
    {
      "word": "DUMBBL",
      "description": "Short handheld weight used for unilateral strength exercises."
    },
    {
      "word": "KETTLE",
      "description": "Cast-iron ball weight with handle swung for explosive power."
    },
    {
      "word": "MEDBAL",
      "description": "Heavy weighted medicine ball slammed for core power."
    },
    {
      "word": "SPEEDO",
      "description": "Streamlined performance swimwear worn by competitive swimmers."
    },
    {
      "word": "GOGGLE",
      "description": "Watertight eyewear providing underwater visibility for swimmers."
    },
    {
      "word": "STRIDE",
      "description": "Long fluid running step optimizing sprint biomechanics."
    },
    {
      "word": "PILING",
      "description": "Defensive goal-line stand piling bodies atop the football."
    },
    {
      "word": "CENTER",
      "description": "Position anchoring the offensive line in football or basketball key."
    },
    {
      "word": "SWORDS",
      "description": "Blades wielded in competitive fencing duels."
    },
    {
      "word": "FOILED",
      "description": "Light thrusting sword used in sport fencing bouts."
    },
    {
      "word": "EPEESZ",
      "description": "Heavier dueling sword with triangular blade in fencing."
    },
    {
      "word": "SABRES",
      "description": "Cutting and thrusting weapon in Olympic fencing."
    },
    {
      "word": "DUGOUT",
      "description": "Low shelter where baseball players sit during games."
    }
  ]
};

export function getCategoryPool(categoryId?: string): WordItem[] {
  if (!categoryId || categoryId === 'anything' || !(categoryId in categoryWords)) {
    return [
      ...categoryWords.space,
      ...categoryWords.animals,
      ...categoryWords.food,
      ...categoryWords.sports,
    ];
  }
  return categoryWords[categoryId as keyof typeof categoryWords];
}
